name: "打卡"

# 明确触发条件
on:
  workflow_dispatch:  # 手动触发
  # schedule:
  #   # 使用 UTC 时间，UTC 时间 对应 北京时间 -8 小时
  #   - cron: "0 0 * * *"  # UTC 00:00 / 北京时间 08:00
  #   - cron: "0 1 * * *"  # UTC 01:00 / 北京时间 09:00
  #   - cron: "0 9 * * *"  # UTC 09:00 / 北京时间 17:00
  #   - cron: "0 10 * * *" # UTC 10:00 / 北京时间 18:00

# 配置并发控制，避免任务重叠执行
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 添加超时限制

    steps:
      # 设置时区为 Asia/Shanghai
      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Shanghai"

      # 检出代码仓库
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # 优化克隆深度

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'  # 启用 pip 缓存
          check-latest: true  # 检查是否有更新的补丁版本

      # 缓存 pip 依赖
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      # 写入 Secrets 到 JSON 文件
      - name: 写入 Secrets 到 config.json
        env:
          #HYF: ${{ secrets.HYF_JSON }}
          #LM:  ${{ secrets.LM_JSON  }}
          # ZXS: ${{ secrets.ZXS_JSON }}
          # BLQ: ${{ secrets.BLQ_JSON }}
          # if [ -z "$HYF" ] || [ -z "$LM" ] ; then
        run: |
          mkdir -p user
          if [ -z "$HYF" ] || [ -z "$LM" ] ; then
            echo "Secrets 为空，请检查配置！"
            exit 1
          fi
          echo "$HYF" > user/config.json
          echo "$LM" > user/config1.json
          echo "写入完成。"

      # 验证 JSON 文件是否正确写入
      - name: 验证 JSON 文件是否正确写入
        run: |
          for file in user/config*.json; do
            if [ -s "$file" ]; then
              echo "文件 $file 已成功写入，大小为：$(stat -c%s "$file") 字节"
              python -m json.tool "$file" > /dev/null
              if [ $? -ne 0 ]; then
                echo "文件 $file 不是合法的 JSON 格式！"
                exit 1
              fi
            else
              echo "文件 $file 写入失败或为空！"
              exit 1
            fi
          done

      # 执行任务
      - name: Run sign in script
        env:
          USER: ${{ secrets.USER }}
          TZ: Asia/Shanghai  # 确保脚本运行时也使用正确的时区
        run: |
          python main.py
